### ISSUE TITLE
How could I test on common 3 channel RGB images?

### ISSUE THREAD

**Issue by aligoglos** [aiff22/PyNET#3]
I tried on a `448*448*3 `PNG image but this error occurred :
```
Traceback (most recent call last):
  File "test_model.py", line 67, in <module>
    I = np.reshape(I, [1, I.shape[0], I.shape[1], 4])
  File "<__array_function__ internals>", line 6, in reshape
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\127051\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 602112 into shape (1,224,224,4)
```

**Comment by aiff22** [comment]
Hi @aligoglos,

In the considered task, the model is trained to reconstruct RGB photos from the RAW camera images, therefore it should be applied only to raw Bayer data:

https://en.wikipedia.org/wiki/Bayer_filter

If you are interested in general image quality enhancement, please take a look at the following github repository:

https://github.com/aiff22/DPED
